site_name: FreeFlarum Documentation
site_url: https://docs.freeflarum.com/

theme:
  name: material
  language: en
  logo: /images/freeflarum-logo-small.png
  favicon: /images/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - toc:
      permalink: ⚓︎

plugins:
  - search
  

repo_url: https://github.com/FreeFlarum/freeflarum.com
