site_name: FreeFlarum Documentation
site_url: https://freeflarum.com/docs/
  
theme:
  name: "material"

  language: en
  palette:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: '/docs/'
  - About: 'about.md'
  - FaQ: 'faq.md'
  - Troubleshooting: 'troubleshooting.md'
  - Roadmap: 'roadmap.md'
  - Tutorials:
    - 'Exporting Your Forum': 'tutorials/exporting-forum.md'
    - 'Custom Domain': 'tutorials/linking-custom-domain.md'
    - 'Configuring Mail': 'tutorials/configuring-mail.md'
  - Legal:
    - 'Privacy Policy': 'legal/privacy-policy.md'
    - 'Terms': 'legal/terms.md'

extra_css:
  - 'extra/freeflarum.css'

markdown_extensions:
  - admonition
  - toc:
      permalink: ⚓︎

plugins:
  - search
  
repo_url: https://github.com/gwillem/freeflarum.com

