site_name: FreeFlarum Documentation
site_url: https://www.freeflarum.com/docs/

theme:
   name: 'material'
   #  custom_dir: theme

# -----------------------------------------------
# need to enumerate everything, see this issue:
# https://github.com/mkdocs/mkdocs/issues/714
# -----------------------------------------------
nav:
  - home: 'https://www.freeflarum.com/docs/'
  - about: 'about.md'
  - faq: 'faq.md'
  - roadmap: 'roadmap.md'
  - getting started:
    - basics:
        - 'how-to/basics/create-account.md'
        - 'how-to/basics/personalization.md'
        - 'how-to/basics/private-forum.md'
  - extensions:
    - 'how-to/extensions/about-extensions.md'
    - extension list:
        - 'how-to/extensions/analytics.md'
        - 'how-to/extensions/approval.md'
        - 'how-to/extensions/arabic-language.md'
        - 'how-to/extensions/bbcode.md'
        - 'how-to/extensions/bosanski.md'
        - 'how-to/extensions/bosnian-extended-pack.md'
        - 'how-to/extensions/brazilian-portuguese.md'
        - 'how-to/extensions/canonical-url.md'
        - 'how-to/extensions/deutsch.md'
        - 'how-to/extensions/discussion-views.md'
        - 'how-to/extensions/dutch.md'
        - 'how-to/extensions/embed.md'
        - 'how-to/extensions/emoji.md'
        - 'how-to/extensions/english.md'
        - 'how-to/extensions/facebook-login.md'
        - 'how-to/extensions/flagrow-sitemap.md'
        - 'how-to/extensions/flags.md'
        - 'how-to/extensions/fof-bbcode-details.md'
        - 'how-to/extensions/fof-ban-ips.md'
        - 'how-to/extensions/fof-byobu.md'
        - 'how-to/extensions/fof-default-group.md'
        - 'how-to/extensions/fof-default-user-preferences.md'
        - 'how-to/extensions/fof-discord-login.md'
  - third-party integrations:
    - analytics:
        - 'how-to/integrations/google-analytics.md'
    - logins:
        - 'how-to/integrations/google-login.md'
        - 'how-to/integrations/facebook-login.md'
        - 'how-to/integrations/github-login.md'
        - 'how-to/integrations/discord-login.md'
        - 'how-to/integrations/laravel-passport.md'
  - advanced usage:
    - 'how-to/advanced-setup/export.md'
    - 'how-to/advanced-setup/custom-domain.md'
    - 'how-to/advanced-setup/configuring-mail.md'
  - legal:
    - 'legal/privacy-policy.md'
    - 'legal/terms.md'

markdown_extensions:
  - admonition
  
repo_url: https://github.com/gwillem/freeflarum.com
# edit_uri is not required for github