site_name: FreeFlarum Documentation
site_url: https://freeflarum.com/docs/
  
theme:
  name: "material"
  custom_dir: theme/

  language: en
  palette:
    scheme: slate
    primary: black
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: 'https://freeflarum.com/docs/'
  - About: 'about.md'
  - FaQ: 'faq.md'
  - Troubleshooting: 'troubleshooting.md'
  - Roadmap: 'roadmap.md'
  - Tutorials:
    - 'Exporting Your Forum': 'tutorials/exporting-forum.md'
    - 'Custom Domain': 'tutorials/linking-custom-domain.md'
    - 'Configuring Mail': 'tutorials/configuring-mail.md'
  - Legal:
    - 'Privacy Policy': 'legal/privacy-policy.md'
    - 'Terms': 'legal/terms.md'

extra_css:
  - 'theme/style/freeflarum.css'

markdown_extensions:
  - admonition
  - toc:
      permalink: ⚓︎

plugins:
  - search
  
repo_url: https://github.com/gwillem/freeflarum.com

