blank_issues_enabled: false
contact_links:

  - name: Flarum Discuss
    url: https://discuss.flarum.org
    about: Please, ask questions about Flarum there. This repository is intended for FreeFlarum related issues only.
