# Requests users to follow the templates:
blank_issues_enabled: false
contact_links:
#...or links in general. Makes sure people stay to the topic on FreeFlarum.
  - name: Have questions about Flarum in general?
    url: https://discuss.flarum.org
    about: Please, ask questions about Flarum there. This repository is intended for FreeFlarum related issues only.
