name: Build documentation
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: ['en', 'cn']

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: docs.freeflarum.com
          CONFIG_FILE: docs/${{ matrix.language }}.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: requirements.txt
