name: Build documentation
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Build docs
        run: bash deploy.sh
      
      - run: |
          echo "docs.freeflarum.com" > ./build/CNAME
          echo '<meta http-equiv="refresh" content="0; url=/en"/><a href="/en">Redirect</a>' > ./build/index.html

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
