name: Build documentation
on:
  push:
    branches:
      - main

jobs:
  languages_matrix:
    strategy:
      matrix:
        language: ['en', 'cn']

  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: docs.freeflarum.com
          CONFIG_FILE: ${{ matrix.language }}/mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: requirements.txt
