name: Build MkDocs 
on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: 'pip'

      - run: |
          pip install -r requirements.txt
          mkdocs gh-deploy --force
